### ISSUE TITLE
Handeling history when components are removed?

### ISSUE THREAD

**Issue by zam6ak** [brunotavares/Ext.ux.Router#1]
Hi

I was wondering how would I handle routing for components that are removable?
For example, adding multiple closeable tab panels....Eg. add(1), add(2), add(3) - three panels show in tabpanel.
Now let;s say user closes #2 tab, and then uses browser's back/forward button....

Any ideas as to what is the best way to handle this with Routing?

**Comment by brunotavares** [comment]
I had this situation with windows instead of tabpanels. Considering that the main view is /clients, and the tabpanel are projects from this client, like /clients/projects/1, when the project tab is closed I'd redirect back to /clients. 

```
tab.on('destroy', function() { Ext.ux.Router.redirect('clients'); })
```

This would force the history to a new /clients page, but you're logic could enforce that if a Clients view is already created, you don't create a new one. So basically you're just changing the URL, but not the views.

Since the URL hash changed, if the user presses back, it will go back to /clients/projects/1, firing up the logic to recreate the tab.

This is just ONE idea. The other one will be adjust the redirect method to pass a "ignoreEvents" flags that would only change the URL, without firing up the routing dispatch routine. This would be a more elegant solution, but more advanced too.

**Comment by zam6ak** [comment]
Thanks for the reply....

Recreating the tab after it has been closed would be a "walk in the park" if it was desirable.
In my case however, it is not :)

When user navigates back/forth with browser and "arrives" at the route of the view that was closed it needs to be "skipped" without re-creating the view.I think your approach with options in redirect method can work, but I also think the major pain here is the History itself (there is no way to remove history items).

**Comment by brunotavares** [comment]
You can use Ext.History.back() and forward(). So you redirect the user back and then close the tab. Every time a tab is closed it fires the event 'close' that you can use. Or even 'beforeclose', to redirect before closing.

**Comment by zam6ak** [comment]
That is exactly what I am doing. However, the issue is that the history on closed component is preserved, so when user navigates forward it is being recreated which is not desired. The problem is that current Ext.History does not allow you to remove history entry (which is what would be desired when component is destroyed), essentially allowing "skipping".

**Comment by brunotavares** [comment]
Ok, I don't know exactly what your situation is, but I believe there's 2 solutions for that. Unfortunately none will match exactly the desirable History skip() or pop(), but we can workaround it.

One is using a validation. Let's say I have a route to "products/1", but after deleting this product, the user can't go back. In this case I'd put a validation on the route to check if the product "1" exists, and if not, redirect the user to the products lists "/products".

The second case is, not create a route at all for this action. If this action is something you don't want your users to go back, don't provide them with an URL for it. This way you'd enforce your users to the action by following your UI flow.
