### ISSUE TITLE
Adding viewModel/config data on redirect...

### ISSUE THREAD

**Issue by zam6ak** [brunotavares/Ext.ux.Router#3]
I am struggling to figure out how to add additional view model data when doing redirect without making it part of the route variables. For example, consider a grid backed by a store/model that has id, name, cat_id, cat_name (i.e. "item belongs to category"). When "add new" button is clicked, I can get the selection model of the row and "construct" the desired route, and then redirect. For example, 

Ext.ux.Router.redirect('/categories/' + cat_id + 'items/new');

In controller then, this route would map to some function  (e.g. newItem(params), where I can use params.cat_id)...
But what if I wanted to set title of the window to say ("Add new item to {cat_name}")....

Is there a way to pass parameters without including them in the route?
BTW, I know I could retrieve the title in the action by calling the store again with given id...

It would be nice if I could optionally pass in entire view model to redirect....
Taking it even further (I know, I may be daydreaming :)), something like:

Ext.ux.Router.redirect('_route_name_', viewModel); 
// the above would create a route by looking it up (by some id/name) and replacing prams with matching values from view model
// it would also pass the entire viewModel to action

**Comment by brunotavares** [comment]
I believe getting the full model from the datastore is a better approach then adding this to your route. Passing extra params that don't go into the URL will only work if the users follows your app flow. If he lands directly on the page, the model won't be there. 

That's why I like the approach of leaving these specifics to the controller to handle. He'll be the one to get the data from the datastore, where it belongs, and check if it exists or not.
