### ISSUE TITLE
Unable to use Sencha Cmd with Ext.ux.Router

### ISSUE THREAD

**Issue by zam6ak** [brunotavares/Ext.ux.Router#5]
When I try to compile my app with Sencha Cmd, it fails to find Ext.ux.Router.js because it is not returning object literal.

Here the output.

```
X:\Source\MyApp>sencha compile -classpath=lib/extjs/src,lib/ux,app page -yui -in index.html -out build/index.html
Sencha Cmd v3.0.0.190
[INFO ]         Compiling page null
[INFO ]         Processing classPath entry : X:\Source\MyApp\sencha-compile-temp-dir
[INFO ]         Processing classPath entry : lib\extjs\src
[INFO ]         Processing classPath entry : lib\ux
[INFO ]         Processing classPath entry : app
[WARN ]         [ [1003] : Unsupported Ext.define syntax <> function does not return object literal ] :: ( X:\Source\MyApp\lib\ux\Router.js => 43 : 0 )
[INFO ]         Processing class inheritance graph
[INFO ]         Processing instantiation refereces to classes and aliases
[WARN ]         [ [1003] : Unsupported Ext.define syntax <> function does not return object literal ] :: ( X:\Source\MyApp\lib\ux\Router.js => 43 : 0 )
[INFO ]         Processing source dependencies
[ERROR]         Failed to find file for Ext.ux.Router required by X:\Source\MyApp\app.js
[ERROR]         Error executing page compilation Failed to find any files for Ext.ux.Router
[ERROR]         com.sencha.exceptions.ExBuild: Failed to find any files for Ext.ux.Router
```

**Comment by brunotavares** [comment]
Sencha CMD 3 is not finding Ext.ux.Router. The new CMD does not uses the Ext.Loader.setPath to resolve the files and dependencies.

You need to add Router.js to your app.classpath inside .sencha directory. Example

app.classpath=${app.dir}/app,${app.dir}/../../Router.js

Let me know if that worked for you.

**Comment by zam6ak** [comment]
I am not sure this is the case - the Ext.ux.Router is being found, the problem is that SenchaCmd is not processing it because it does not return object literal. I tested this by hacking it so it would return object literal and the error went away (not that I would want to use my own hack, it certainly is not very good).

Also, what happens when I want to use other Ext.ux.\* extensions. Currently SenchaCmd "preps" an ext/ folder where it copies all src/ux/ files under /ext/ux....Your recommendation is to keep Ext.ux.Router in a different location and then tell the command to use it. But during development when we are supposed to use Loader this is quite difficult because I cannot map the namespace Ext.ux to 2 different folders - can I?

Lastly, I think issue should not be closed before submitter had a chance to test it first ?

**Comment by brunotavares** [comment]
1 - Yes, the version 1.0 was using an anonymous class in order to create the singleton. If you try to use v1 with the new Sencha Command 3, it will complain about object literal, etc... 

I changed to a more conventional way on 2.0. The example available inside /examples here are using the new Sencha Cmd 3.

2 - When you map Ext.ux.Router to your path, command knows where this class is. All other Ext.ux.\* are inside ext/ux, but Ext.ux.Router is inside the path you specify. You can check this by opening my example and typing in your console

Ext.Loader.getPath("Ext.ux.BoxReorderer")

> > > "../ext/src/ux/BoxReorderer.js"

Ext.Loader.getPath("Ext.ux.Router")

> > > > "../../Router.js"

As you can see, different classes from the same Ext.ux package might point to different locations.

Lastly, sorry about closing, but it's my understanding that this issue is solved and tested against the example provided. If it's a bug and it starts happening again, feel free to reopen. No problem with that.

**Comment by zam6ak** [comment]
Thanks for the detailed answer.  When can we expect 2.0? :)

**Comment by brunotavares** [comment]
It's out already :) I committed 8 days ago.  http://extdesenv.com/extensions/new-routing-system-for-ext-js/
